


logOutputIntervalSeconds: 1
startupDelay: 3000

read:
  threads: 1
  filename: testreadfile
  filesize: 10485760
  chunkSize: 8192
  durationSeconds: 60
  
write:
  threads: 1
  filename: testwritefile
  filesize: 10485760
  chunkSize: 8192
  durationSeconds: 60
  
  

# Spring Actuator Config
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: FULL
